### ISSUE TITLE
discussion threads do not load automatically

### ISSUE THREAD

**Issue by WangQiru** [iosOctohub/feedback#1]
“discussion” does not load automatically upon entering the issue/pull, a pull down to refresh gesture is required to display the threads.

Env:
iPhone X
iOS 11.2.5

**Comment by martinpucik** [comment]
Hey @WangQiru 
Thanks for the feedback!

Yeah, this was an issue with syncing, but it should be fixed in version 1.2.1 that should be now live in the AppStore.

If you can confirm, that this fix is working for you, that would be awesome!

**Comment by WangQiru** [comment]
Yep 1.2.1 fixed this issue #1.

**Comment by martinpucik** [comment]
Awesome, thank you @WangQiru !
