### ISSUE TITLE
[not huginn related] Description page sometimes shows a blank page 

### ISSUE THREAD

**Issue by WangQiru** [iosOctohub/feedback#2]
Description does not load for some issue/pull.

Eg: https://github.com/huginn/huginn/issues/2208

![4b6618ea-6da0-4785-bafa-896abd5c8a50](https://user-images.githubusercontent.com/5896343/35837279-f086a6a2-0adc-11e8-9a7d-30b62d22e476.jpeg)

Env:
iPhone X
iOS 11.2.5

**Comment by WangQiru** [comment]
Ironically, this issue includes this issue XD

**Comment by martinpucik** [comment]
Thanks for the report @WangQiru!
I can't reproduce this, but I think this could be resolved in v1.2.1 as well as #1 
Please, let me know if the update fixed this.

**Comment by martinpucik** [comment]
@WangQiru nope, found the issue, will be fixed in next release!

**Comment by kstrib** [comment]
How and why am I seeing this?

**Comment by martinpucik** [comment]
@WangQiru should be fixed in new version now!
