### ISSUE TITLE
Can’t login

### ISSUE THREAD

**Issue by thespacedoctor** [iosOctohub/feedback#3]
#### What's not working for you?

- 

### Configuration

- **App Version:** 
- **iPhone Type:** 
- **iOS Version:** 

### Screens

> If you can provide some screenshots for the issue, it would be awesome and helpful in resolving it

**Comment by thespacedoctor** [comment]
Sorry details got cleared before I submitted - iPhone SE, iOS 11.x, app v1.2.5

I get a failed to load user for gained access token - but with credientials and with a personal access token

**Comment by martinpucik** [comment]
Hey David.
Sorry for the issue, but fix should be released in next few days. There is small bug in data parsing expecting user's bio as non-optional 🙄. For workaround you could fill your Github bio.

**Comment by martinpucik** [comment]
@thespacedoctor the fix should be now live on the AppStore in version 1.2.6 👍

**Comment by thespacedoctor** [comment]
Speedy!

**Comment by tooomm** [comment]
I have the same problem. Just downloaded and freshly installed on iOS 11.4.1

I don't see the version in the app since there is just the login button which always tells me "Failed", but the app is added to GitHub OAuthApps in my account settings!
